query describelocalvolumes(
    $Action: String!,
    $Version: String!,
    $InstanceName: String,
    $Marker: Float,
    $MaxResults: Float,
    $test: Boolean
) {
    describelocalvolumes(
    Action: $Action,
    Version: $Version,
    InstanceName: $InstanceName,
    Marker: $Marker,
    MaxResults: $MaxResults,
    test: $test
    ) {
        RequestId
        Marker
        MarkerCount
        InstanceList {
            ...InstanceListData
        }
        DBList {
            ...DBListData
        }
        UserInfo {
            name
            age
        }
    }
}

fragment InstanceListData on ResdescribelocalvolumesInstanceListItem {
    InstanceName
    InstanceStatus
    Memory
    CPU
    Tag
    arrayObj {
        arrayObjName
        arrayObjAge
    }
    arrayList {
            ...arrayListData
        }
}

fragment arrayListData on ResdescribelocalvolumesarrayListItem {
    arrayListName
    arrayListAge
}

fragment DBListData on ResdescribelocalvolumesDBListItem {
    DBname
    DBstatus
}